package notes

import (
	"path/filepath"
	"strings"
)

// The vault was markdown-only, and `.md` was asserted in a dozen places:
// the write guard, the walk filter, the template lister, the link
// scanner. Project documentation is increasingly shipped as HTML —
// exported from Notion or Word, generated by typedoc / asciidoc /
// Sphinx — and a doc library that cannot open those is not a doc
// library, it is a markdown library.
//
// So "what counts as a document" is decided here, once. Adding a format
// later means touching this file, not hunting for `.md` again.
//
// Note what is deliberately NOT symmetric between the two kinds:
//
//   - `[[wiki links]]` are scanned in MARKDOWN ONLY. HTML has real
//     <a href> links, and rewriting those on a move is a different job
//     with different failure modes (relative paths, anchors, assets).
//     An HTML file can still be the TARGET of a wiki link from a
//     markdown note — that direction costs nothing and is useful.
//   - auto-derived paths (daily notes, project notes) stay `.md`.
//     Those are written by agents and by opendray itself; markdown is
//     the right default and HTML would be a strange thing to generate.

// Kind classifies a document by extension. It drives which renderer a
// client reaches for, and clients derive it from the path rather than
// asking the server — which is what keeps HTML off any opendray-served
// origin. See the sandboxing note in the web/mobile viewers.
type Kind string

const (
	// KindMarkdown renders through the markdown pipeline.
	KindMarkdown Kind = "markdown"
	// KindHTML renders inside a sandboxed frame with scripts off.
	KindHTML Kind = "html"
	// KindUnknown is anything the vault does not treat as a document.
	KindUnknown Kind = ""
)

// extKinds maps a lower-cased extension to its kind. The single source
// of truth for "is this a document".
var extKinds = map[string]Kind{
	".md":       KindMarkdown,
	".markdown": KindMarkdown,
	".html":     KindHTML,
	".htm":      KindHTML,
}

// KindOf classifies a vault path. Unknown extensions return KindUnknown.
func KindOf(rel string) Kind {
	ext := strings.ToLower(filepath.Ext(rel))
	// A bare ".md" is a dotfile, not a document with an empty name.
	// Go's filepath.Ext happily calls it an extension, and without this
	// the write guard would accept a file the listing then skips as
	// hidden — writable but invisible.
	if strings.TrimSuffix(filepath.Base(rel), filepath.Ext(rel)) == "" {
		return KindUnknown
	}
	return extKinds[ext]
}

// IsDocument reports whether a path is one the vault stores and lists.
func IsDocument(rel string) bool { return KindOf(rel) != KindUnknown }

// IsMarkdown reports whether a path participates in wiki-link scanning
// and rewriting.
func IsMarkdown(rel string) bool { return KindOf(rel) == KindMarkdown }

// TrimDocExt removes a known document extension, leaving the wiki-link
// target form. Unknown extensions are left alone, so a stray path never
// silently becomes a link target for something else.
func TrimDocExt(rel string) string {
	ext := strings.ToLower(filepath.Ext(rel))
	if _, ok := extKinds[ext]; ok {
		return rel[:len(rel)-len(ext)]
	}
	return rel
}

// DocExtensions lists the accepted extensions, for error messages and
// for the clients' "new document" pickers.
func DocExtensions() []string {
	return []string{".md", ".markdown", ".html", ".htm"}
}
